name: Publish
on:
  release:
    types: [published]

env:
  FORCE_COLOR: 3

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Build WASM
        run: pnpm run build

      - name: Patch packages
        run: ./scripts/patch-packages.sh ${{ github.ref_name }}

      - name: Show package contents
        run: |
          cat ./packages/client/package.json
          cat ./packages/server/package.json

      - name: Publish NPM packages
        run: pnpm publish --recursive --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ github.token }}
          SCEAU_PRIVATE_KEY: ${{ secrets.SCEAU_PRIVATE_KEY }}
